name: Build and Run Java JAR in GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Print JAR File Name
        run: echo "The generated JAR file is: target/$(basename target/*.jar)"

      - name: Run JAR file
        run: java -jar target/$(basename target/*.jar)
