name: Build and Run JAR

# Trigger the workflow on trigger manually
on:
  workflow_dispatch:  # Manually trigger the workflow from the GitHub UI

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up JDK 11 (or any other version you need)
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    # Step 3: Build the project with Maven
    - name: Build with Maven
      run: mvn clean package -DskipTests

    # Step 4: Run the JAR file
    - name: Run the JAR file
      run: java -jar target/your-project-1.0-SNAPSHOT.jar
